# Spencer Porter's Capstone

Goals

Idea #1

My general Capstone idea is around cyclists and the number of accidents in x cities. I haven't decided if I want to limit my research to just SF or expand it to include NYC, LA, CHI, and perhaps a foreign city, depending on if I can get my hands on the data set.

I will use this cycling data to find a relationship between the number of cyclists on the road and the number of cycling accidents. I'd like to see if there is a correlation between the rates of cycling accidents and the types of riders in each city, i.e if there are more 'serious' riders than 'casual' commuters in SF, will that translate to mean there are fewer accidents per capita since the serious 'riders' are presumably more comfortable on the road and with traffic laws, etc.?

I want to also gather weather data to find a correlation between non-ideal weather conditions/time of year and peaks in cycling accidents. 

Ultimately I'd like to arrive to a conclusion about what city is the most unsafe for cyclers as well as what time of year will produce the highest likelihood of being involved in an accident.

Idea #2

I'd leverage the cyclist count data from the first idea but then also incorporate bike theft data from different cities. I found a dataset that has crime data by neighborhood, so I'd use that information to predict the likelihood of getting your bike stolen for different cities, and different neighborhoods.

Idea #3

Music

-types of music over 10 year timeframe for x number of major music festivals

-which genres were the most popular vs. which are becoming the most popular?

-the demographics of the festivals and how that could have an impact on the type of music being played at the festivals

Links to datasets: 

SF crime data: https://data.sfgov.org/Public-Safety/SFPD-Incidents-from-1-January-2003/tmnf-yvry

NY crime data: https://data.cityofnewyork.us/Public-Safety/NYPD-Motor-Vehicle-Collisions/h9gi-nx95/data

In [31]:
#NYC crime dataset that includes columns about cyclist accidents

import pandas as pd
import numpy as np

bikes = pd.read_csv("../../../Desktop/datasets/NYPD_Motor_Vehicle_Collisions.csv")
crime = pd.read_csv("../../../Desktop/datasets/SFPD_Incidents_-_from_1_January_2003.csv")

In [38]:
bikes.head()

,DATE,TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,UNIQUE KEY,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5
0,11/10/2016,15:11,NaN,NaN,NaN,NaN,NaN,MONROE STREET,NaN,NaN,...,Unspecified,NaN,NaN,NaN,3559084,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
1,04/16/2016,4:13,NaN,NaN,40.767373,-73.950057,"(40.767373, -73.9500574)",EAST 68 STREET,NaN,NaN,...,Fatigued/Drowsy,Fatigued/Drowsy,NaN,NaN,3408932,PASSENGER VEHICLE,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN
2,04/16/2016,4:22,NaN,NaN,NaN,NaN,NaN,BORDEN AVENUE,58TH STREET,NaN,...,NaN,NaN,NaN,NaN,3425902,NaN,NaN,NaN,NaN,NaN
3,04/16/2016,4:30,BRONX,10468.0,40.862679,-73.909040,"(40.8626793, -73.9090397)",SEDGWICK AVENUE,WEST FORDHAM ROAD,NaN,...,NaN,NaN,NaN,NaN,3414396,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
4,04/16/2016,4:30,BROOKLYN,11249.0,40.716508,-73.961275,"(40.7165078, -73.9612751)",NaN,NaN,203 BERRY STREET,...,Unspecified,NaN,NaN,NaN,3421852,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN

In [39]:
crime.head()

,IncidntNum,Category,Descript,DayOfWeek,Date,Time,PdDistrict,Resolution,Address,X,Y,Location,PdId
0,150013666,DRUG/NARCOTIC,POSSESSION OF BASE/ROCK COCAINE,Monday,01/05/2015,15:55,NORTHERN,"ARREST, BOOKED",800 Block of OFARRELL ST,-122.418751,37.785116,"(37.7851160049429, -122.418751252829)",15001366616621
1,150013666,DRUG/NARCOTIC,POSSESSION OF BASE/ROCK COCAINE FOR SALE,Monday,01/05/2015,15:55,NORTHERN,"ARREST, BOOKED",800 Block of OFARRELL ST,-122.418751,37.785116,"(37.7851160049429, -122.418751252829)",15001366616623
2,150026528,WEAPON LAWS,POSSESSION OF AIR GUN,Friday,01/09/2015,14:36,MISSION,"ARREST, BOOKED",24TH ST / MISSION ST,-122.418448,37.752239,"(37.7522391652625, -122.418448186101)",15002652830140
3,150026534,SUSPICIOUS OCC,SUSPICIOUS OCCURRENCE,Thursday,01/08/2015,11:30,RICHMOND,UNFOUNDED,600 Block of 24TH AV,-122.483526,37.777262,"(37.7772616227854, -122.483525546157)",15002653464070
4,150377989,SUSPICIOUS OCC,INVESTIGATIVE DETENTION,Friday,05/01/2015,04:32,CENTRAL,NONE,1100 Block of FILBERT ST,-122.418415,37.800181,"(37.8001811328442, -122.418414919778)",15037798964085